Add .clangd file
friendlyanon/cmake-init pull request #92
Opened 2023-07-28 07:40 UTC by NoahFournier

I've added a default `.clangd` compilation database for people who might be using `vim`/`neovim`. The default `dev` profile will export the compile commands by default, so I think it makes sense to point the default CompilationDatabase to that directory as well.

2023-07-28 13:10 UTC, friendlyanon commented
That seems like a good idea, however the file seems to only work for a single build directory: https://clangd.llvm.org/config#compilationdatabase

The user presets by default already come with many possible build folder locations: https://github.com/friendlyanon/cmake-init/blob/master/cmake-init/templates/common/CMakeUserPresets.json#L17

What I think would work is if this file was also in `.gitignore`, since then multiple users won't clobber each others' setup.

2023-07-28 13:11 UTC, friendlyanon requested changes
Please move this file to `cmake-init/templates/common` and add it to the `.gitignore` file as well.

2023-07-28 13:11 UTC, friendlyanon commented on .clangd
> +  CompilationDatabase: ./build/dev/
If this can just say `build/dev` then please make it so.

2023-08-12 00:52 UTC, friendlyanon commented
Ping

2023-08-13 14:57 UTC, NoahFournier commented
Hey @friendlyanon, have been busy sorry ! Not sure what you mean exactly by adding it `.gitignore`, apologies, I'm not familiar with the internals of cmake-init ! The file is already currently included in the `.gitignore` under `cmake-init/templates/common`.

2023-08-13 17:18 UTC, friendlyanon commented
> The file is already currently included in the `.gitignore`

I haven't noticed! Then please do the other requested changes.

2023-08-20 15:17 UTC, merged